"""
Care Plan Agent: Formulates structured, policy-governed post-care plans
based on external ML readmission model predictions.
"""

from typing import Any, Dict, Optional, Union
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.language_models.chat_models import BaseChatModel
from ..policies.care_policies import get_default_policy_for_risk, CarePolicyConfig
from ..state.patient_state import PatientState, PatientStateModel, RiskLevel, PlanStatus, MonitoringFrequency
from ..config.llm_config import get_llm


class StructuredCarePlan(BaseModel):
    """
    Strongly typed care plan generated by the Care Plan Agent.
    All medical thresholds and monitoring cadences are strictly governed by clinical policy.
    """
    patient_id: str = Field(..., description="Unique patient identifier")
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Readmission probability from external ML model")
    risk_level: str = Field(..., description="Assigned risk tier: LOW, MEDIUM, HIGH, CRITICAL")
    total_care_duration_days: int = Field(..., ge=1, description="Assigned post-care duration from external ML model (NOT fixed to 30 days)")
    current_day: int = Field(default=0, ge=0, description="Starting journey day (initialized to 0)")
    monitoring_frequency: str = Field(..., description="Assigned monitoring cadence")
    daily_checkin_required: bool = Field(default=True, description="Whether daily check-in is mandatory")
    symptom_monitoring_strategy: Dict[str, Any] = Field(..., description="Symptom tracking regimen")
    medication_monitoring_strategy: Dict[str, Any] = Field(..., description="Medication adherence tracking protocol")
    followup_strategy: Dict[str, Any] = Field(..., description="Clinician touchpoint and review schedule")
    escalation_policy_reference: Dict[str, Any] = Field(..., description="Deterministic escalation thresholds and contacts")
    patient_guidance_summary: Optional[str] = Field(default=None, description="Personalized patient-facing non-clinical explanation")


class CarePlanAgent:
    """
    Care Plan Agent responsible for synthesizing structured post-care plans
    governed by clinical policies and ML readmission risk predictions.
    """

    def __init__(self, llm: Optional[BaseChatModel] = None):
        self._llm = llm

    @property
    def llm(self) -> BaseChatModel:
        if self._llm is None:
            self._llm = get_llm()
        return self._llm

    def generate_care_plan(
        self,
        patient_id: str,
        risk_score: float,
        risk_level: Union[str, RiskLevel],
        care_duration_days: int,
        clinical_notes: Optional[str] = None,
    ) -> StructuredCarePlan:
        """
        Synthesizes a structured care plan.
        Clinical policies dictate thresholds; the LLM provides optional patient-friendly explanation.
        """
        # Validate and normalize risk tier string
        r_level_str = risk_level.value if isinstance(risk_level, RiskLevel) else str(risk_level).strip().upper()

        if care_duration_days < 1:
            raise ValueError(f"care_duration_days must be >= 1, got {care_duration_days}")

        # 1. Fetch deterministic policy for the risk level (LLM is NOT permitted to alter thresholds)
        policy: CarePolicyConfig = get_default_policy_for_risk(r_level_str)

        # 2. Generate optional personalized non-clinical patient guidance via LLM (with deterministic fallback)
        guidance_text = (
            f"Your customized {r_level_str.lower()}-risk post-discharge care program is set for {care_duration_days} days. "
            f"Please complete your check-in {policy.monitoring_frequency.lower().replace('_', ' ')}."
        )

        try:
            sys_prompt = (
                "You are an empathetic medical assistant explaining a post-discharge care plan to a patient. "
                "Provide a 2-sentence encouraging, non-clinical summary. "
                "Do NOT invent new medical instructions or thresholds."
            )
            user_content = (
                f"Patient: {patient_id}. Risk Tier: {r_level_str}. Monitoring Duration: {care_duration_days} days. "
                f"Frequency: {policy.monitoring_frequency}. Notes: {clinical_notes or 'Standard post-discharge recovery'}"
            )
            response = self.llm.invoke([SystemMessage(content=sys_prompt), HumanMessage(content=user_content)])
            if response and response.content and str(response.content).strip():
                guidance_text = str(response.content).strip()
        except Exception:
            # Safe deterministic fallback if LLM is unavailable or unconfigured
            pass

        # 3. Assemble strictly validated StructuredCarePlan
        return StructuredCarePlan(
            patient_id=patient_id,
            risk_score=risk_score,
            risk_level=r_level_str,
            total_care_duration_days=care_duration_days,  # Exactly the duration provided by external model
            current_day=0,
            monitoring_frequency=policy.monitoring_frequency,
            daily_checkin_required=policy.daily_checkin_required,
            symptom_monitoring_strategy=policy.symptom_monitoring_strategy,
            medication_monitoring_strategy=policy.medication_monitoring_strategy,
            followup_strategy=policy.followup_strategy,
            escalation_policy_reference=policy.escalation_policy_reference,
            patient_guidance_summary=guidance_text,
        )

    def initialize_patient_state(
        self,
        patient_id: str,
        risk_score: float,
        risk_level: Union[str, RiskLevel],
        care_duration_days: int,
        clinical_notes: Optional[str] = None,
    ) -> PatientStateModel:
        """
        Directly generates the initial PatientStateModel from external readmission model inputs.
        """
        care_plan = self.generate_care_plan(
            patient_id=patient_id,
            risk_score=risk_score,
            risk_level=risk_level,
            care_duration_days=care_duration_days,
            clinical_notes=clinical_notes,
        )

        r_level_enum = RiskLevel(care_plan.risk_level)
        monitoring_freq_enum = MonitoringFrequency(care_plan.monitoring_frequency)

        return PatientStateModel(
            patient_id=patient_id,
            risk_score=risk_score,
            risk_level=r_level_enum,
            care_duration_days=care_duration_days,  # Enforces variable duration
            current_day=0,
            last_checkin_day=None,
            monitoring_frequency=monitoring_freq_enum,
            care_plan=care_plan.model_dump(),
            symptoms=[],
            medication_adherence=1.0,
            current_action=None,
            next_action="INITIAL_ASSESSMENT",
            escalation_required=(r_level_enum == RiskLevel.CRITICAL),
            previous_actions=[],
            latest_feedback=None,
            feedback_history=[],
            adaptation_notes=[],
            plan_status=PlanStatus.INITIALIZED,
        )
